---

 - name: Arch Linux post-provisioning
   hosts: localhost
   roles:
     - role: packages
       tags:
         - packages
         - postinst
     - role: sddm
       tags:
         - sddm
         - postinst
     - role: services
       tags:
         - services
         - postinst
     - role: plymouth
       tags:
         - plymouth
         - postinst
     - role: chezmoi
       tags:
         - chezmoi
         - dotfiles
         - postinst
     - role: nvim
       tags:
         - nvim
         - dotfiles
         - postinst
     - role: gitconfig
       tags:
         - gitconfig
         - dotfiles
         - postinst
     - role: shell_profile
       tags:
         - shell_profile
         - dotfiles
         - postinst
     - role: plymouth
       tags:
         - plymouth
         - boot
         - postinst
     - role: dracut
       tags:
         - dracut
         - boot
         - postinst

 - name: Reboot
   hosts: localhost
   tasks:
     - name: Reboot the computer
       shell: shutdown -r +1
       changed_when: no
   tags:
     - never
     - postinst
